### PR TITLE
* stream.el (stream-append): New function.

### PR DESCRIPTION
**Pull request by ghost**
Ok, let's start with `stream-append'.

Should I also add tests?  Is it enough to edit stream/test/stream-tests.el for that purpose?

Thanks.

### CODE REVIEW

**Comment by NicolasPetton** [comment]
:+1:  Great!  

And yes, tests can go in stream-tests.el.

**Comment by NicolasPetton** [comment]
@michael-heerdegen could you resolve the conflicts? Otherwise it's good to be merged!

**Comment by ghost** [comment]
Nicolas Petton notifications@github.com writes:

> @michael-heerdegen could you resolve the conflicts? Otherwise it's
> good to be merged!

Of course.

But I'll take the opportunity and rewrite the thing so that it doesn't
request the first element of the first stream (same problem as in the
seq-map implementation).

**Comment by NicolasPetton** [comment]
Oh, right! Thanks in advance.

**Comment by ghost** [comment]
Nicolas Petton notifications@github.com writes:

> Oh, right! Thanks in advance.

Nothing advance, I've already made the pull request.

Michael.

**Pull request merged**
